### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by FerDR89** [gonzaliski/desafio-m6#1]
Buenas!
Estuve tratando de revisar el desafío pero me encontré con el siguiente inconveniente cuando quiero ingresar a una sala recién creada desde otro navegador

Creo la sala:
![image](https://user-images.githubusercontent.com/74626765/177325056-443bce3d-e497-4b6a-b8b4-bf689cd7a369.png)

Trato de ingresar a la sala:
![image](https://user-images.githubusercontent.com/74626765/177324953-09b3a0e9-2598-47a6-90e5-dc5f898b53e5.png)

Creo otra sala y lo mismo
![image](https://user-images.githubusercontent.com/74626765/177325232-0e5e81dd-f1fe-4a18-8e99-b3966df5f2d7.png)

**Comment by gonzaliski** [comment]
Hola Fer! Gracias por revisar, solucionado!
