### ISSUE TITLE
Issues #2

### ISSUE THREAD

**Issue by Alvax10** [gonzaliski/desafio-m6#2]
Buenass gon, como va? entré a tu página para probarla y me pasó esto:

En la página de mi "primer jugador" se ven así las manos:
![Screenshot from 2022-07-05 12-30-25](https://user-images.githubusercontent.com/64299010/177364270-ce689d42-cbe4-47c6-86dc-5b24e3c2ab59.png)
Esto no queda bien visualmente y hace que sea muy dificil tocar el boton, también te recomiendo ponerle el estilo `cursor: pointer` al botón

Peeero, en la página de mi "segundo jugador" se ve bien:
![Screenshot from 2022-07-05 12-30-45](https://user-images.githubusercontent.com/64299010/177364773-051fe231-a7da-4af5-835c-30d57b12b46f.png)

Y luego de crear la sala y querer unirme, se cayó el back:
![Screenshot from 2022-07-05 12-31-28](https://user-images.githubusercontent.com/64299010/177364838-5c28a9e1-58f3-488c-a8c5-4cbd7d24b3b6.png)
 Una nota aparte, este fue el código que me salió: `ib7h1c` me parece un poco "complejo" capaz sería más fácil si son solo numeros o solo letras y que sean máximo 5 o 4 caracteres, hace que el usuario se pueda unir más fácil

**Comment by gonzaliski** [comment]
Buenas Alva! Fijate ahora que hice unos cambios. Lo de que el back se cayó ni idea, a mi me anduvo, raro o.O

**Comment by Alvax10** [comment]
> Buenas Alva! Fijate ahora que hice unos cambios. Lo de que el back se cayó ni idea, a mi me anduvo, raro o.O

Ahora vuelvo a probar gon!
